practicalswift/swift-compiler-crashes

crashes/23172-lowering-silgenfunction-emitapplyexpr.swift
Added human-detected crash when accessing function-level var from a method on an inner class.
=> Crash in emitapplyexpr

crashes/23408-missing-type-in-generic-constraint.swift, crashes/23409-circular-typealias.swift
The first bug appears similar to 21270 (it uses a missing type in a generic constraint clause), but the stack trace is different (21270 crashes at lexing, this one crashes at validation).
At first glance, the second bug appears to have no other similar bug.
=> Adding two new human-detected bugs

crashes/23892-swift-archetypebuilder-resolvearchetype.swift
The definition of the Mu type causes a crash in the `swift::ArchetypeBuilder::resolveArchetype`. This one makes the mad scientist in me quite sad.
=> 23892: Fixpoint Combinator for Types

crashes/23893-swift-irgen-emitObjCExistentialDowncast.swift
Hey @practicalswift, got a new one for ya (or so I think :))! 
`CFDictionary` must be optional for the crash to occur.
=> Added crash - 23893 - IRGen emitObjCExistentialDowncast

crashes/23909-swift-irgen-emitscalarexistentialdowncast.swift
This is identical to [23893](https://github.com/practicalswift/swift-compiler-crashes/pull/51) (which was just fixed in Xcode 6.3 Beta 1), except it uses the newly added forced downcast.
=> Added crash - 23909 - IRGen emitScalarExistentialDowncast

crashes/23910-no-stacktrace.swift
- This was discovered in [SwiftShell](https://github.com/kareman/SwiftShell)
- See issue https://github.com/kareman/SwiftShell/issues/8
- This was working previously (Xcode 6.1.1) so looks to be a compiler regression
- The property type doesn’t seem to matter
- The stack trace contains nothing distinct in it, so I can’t tell if its unique
=> Added crash - 23910 - No stack trace

crashes/24607-swift-irgen-unpackenumpayload-claim.swift
- Discovered in Xcode 6.3b2, still crashes in 6.3b3
=> Add crash 24607-swift-irgen-unpackenumpayload-claim

crashes/24882-extension-generictype-typealias.swift
First time submitting a compiler crash, just using the last crash number + 1. 
Please let me know if there's anything else I need to do.
=> New Swift compiler crash with extension of generic type with type alias

crashes/24883-broken-function.swift
```
Stored value type does not match pointer operand type!
store i8* bitcast (void ()* @globalinit_33_1BDF70FFC18749BAB495A73B459ED2F0_func5 to i8*), i8*** getelementptr inbounds (%P8Contents1X_* @_Tv8Contents1xPS_1X_, i32 0, i32 1), align 8
i8**LLVM ERROR: Broken function found, compilation aborted!
```
=> Added case 24883

crashes/24891-using-utsname-struct.runtime.swift
Crashes at runtime. Regression in **Xcode 7 Beta 1**. Anything besides simply initing the struct seems to cause a crash.
Crash numbering here assumes #74 & #75 are getting merged. If they don't, I can update this PR accordingly.
=> Added runtime crash (regression) - 24891 - using utsname struct

crashes/24889-too-complex-to-be-solved-in-reasonable-time.timeout.swift, crashes/24890-too-complex-to-be-solved-in-reasonable-time.timeout.swift
**24889**
Compiles in Xcode 6.3.2, but quite slowly. It no longer does in Xcode 7 Beta 1, throwing the _"Expression was too complex to be solved in reasonable time"_ error.
**24890**
Similar to 23903 (another _"Expression was too complex.."_ error), however, this was working in Xcode 6.3.2, no longer in Xcode 7 Beta 1, while 23903 was not.
Crash numbering here assumes #74 is getting merged. If it doesn't, I can update this PR accordingly.
=> Add timeout cases 24889 & 24890 - "Expression was too complex..."

crashes/24888-swift-lowering-silgenfunction-emitClosureValue.swift
Crashes in **Xcode 7 Beta 1**, was working in **Xcode 6.3.2**.
The compiler doesn’t seem to like having an inner function taking a generic arg.
=> Added crash (regression) - 24888 - emitClosureValue

crashes/26808-enum-with-indirect-and-function.swift
Outputs
> Command failed due to signal: Segmentation fault: 11
In XCode 7.0 beta 5 (7A176x)
=> Segmentation fault: 11 enum with indirect & func

crashes/26813-swift-irgen-emitPolymorphicArguments.swift
Platform: Apple Swift version 2.0 (swiftlang_PONDEROSA-700.1.100.2 clang-700.1.74)
Target: x86_64-apple-darwin14.5.0
Notes:
- The compiler crashes when generating a signature for CConventionCallback as a child of a generic class.
- The compiler does not crash if myCConventionCallback's definition is moved outside the scope of the generic class.
=> New crash report by christopherhattonuk@gmail.com

crashes/26813-generic-enum-tuple-optional-payload.swift
This crash occurs as of Xcode 7.0 beta 6 (7A192o). If the second argument in the return value is changed to `nil` the function compiles properly.
=> Adding crash related to generic enums with tuple payloads

crashes/27817-anonymous-namespace-rvalueemitter-emitstringliteral.part1.swift, crashes/27817-anonymous-namespace-rvalueemitter-emitstringliteral.part2.swift
Found in xcode7.0.1 and xcode7.1b2
=> Add crash for struct extension with init in another file

crashes/27817-swift-astvisitor.swift
I ran into while tried to use `defer` as a workaround for the failable initialisers requiring calling `super.init` before returning `nil`
=> Add crash for defer in init of subclass

crashes/28071-rawrepresentable-extension-with-initializer.swift
```
$ swift 28071-rawrepresentable-extension-with-initializer.swift
Segmentation fault: 11
```
```
$ xcrun swiftc 28071-rawrepresentable-extension-with-initializer.swift 2>&1 | egrep 'swift.*0x'  | egrep -v '(PrintStackTrace|SignalHandler)' | head -1
```
(produces no output)
=> added RawRepresentable extension crash

crashes/28184-swift-constraints-constraintsystem-gettypeofmemberreference.swift
Found in xcode7.1.1 and xcode7.2b4.
=> Add crash for missing getter in extension property.

crashes/28186-swift-silwitnessvisitor-visitprotocoldecl.swift
This code probably should not compile (there is a type mismatch between the return types on lines 5 and 10), however it crashes the compiler instead of displaying an error. Replacing `Self` with `P` on line 5 results in successful compilation; doing the opposite on line 10 results in a compile error.
% xcrun swiftc crash.swift 2>&1 | egrep 'swift.*0x' | egrep -v '(PrintStackTrace|SignalHandler)' | head -1
4  swift                    0x0000000109aa6707 swift::SILWitnessVisitor<(anonymous namespace)::SILGenConformance>::visitProtocolDecl(swift::ProtocolDecl*) + 999
% xcrun swiftc --version
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
=> Add crash for type mismatch between protocol function and extension

crashes/28187-llvm-foldingset-swift-constraints-constraintlocator.swift
This code should not compile, but instead of giving error it gives segmentation fault 11.
=> Add crash for weak object referenced object method with missing argument.

crashes/28721-irgensilfunction-visitfullapplysite.swift
Tested against Swift version 2.1.1:
```
$ ./test.sh crashes/28721-irgensilfunction-visitfullapplysite.swift
Running tests against: Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Usage: ./test.sh [-v] [-q] [-c<columns>] [-l] [file ...]
Adding a new test case? The crash id to use for the next test case is 28722.
✘  28721 irgensilfunction visitfullapplysite                                                                                                                                                                                                                                                             (87f7985f52)
** Results: 1 of 1 tests crashed the compiler **
```
Problem is also reproduced for similar functions like `map`, `flatMap`.
Normal collections (for example, …
=> Attempt to enumerate Mirror children using forEach with function reference crashes compiler

crashes/28654-swift-lowering-silgenfunction-emitopenexistential.swift
Tested against swift-DEVELOPMENT-SNAPSHOT-2017-01-17-a.
I've also filed a [bug](https://bugs.swift.org/browse/SR-3670).
=> Calling default implementation as a curried method causes a crash

crashes-fuzzing/28247-nominaltypedecl-hasfixedlayout.swift
Tested against Swift 3.1 release (GM Xcode 8.3) and filed [here](https://bugs.swift.org/browse/SR-4390).
=> Using nested typealias from a generic struct causes a crash

README.md, crashes/28736-anonymous-namespacesilverifier-require.swift
Tested on current swift master [be985b1ec701e12c9c02cd1a7933759a15b68a71](https://github.com/apple/swift/commit/be985b1ec701e12c9c02cd1a7933759a15b68a71)
Originally found (with different stack trace) on Swift 3.1 in github.com/giginet/JSONMatcher project during `pod lib lint`, then reduced and reported as [SR-4549](https://bugs.swift.org/browse/SR-4549). Then further reduced with Swift master to this very minimal repro of a compiler crash. I just verified this latest repro crashes on Swift 3.1 as well (with different stack trace).
=> Add crash (recursive generic function call with `[Any]?` argument)
